-- public.todos 테이블 생성
CREATE TABLE public.todos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users NOT NULL,
    task text,
    is_completed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- public.todos 테이블에 대한 RLS (Row Level Security) 활성화
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- 사용자가 자신의 todos만 SELECT (조회)할 수 있는 정책
CREATE POLICY "Enable read access for authenticated users" ON public.todos
AS PERMISSIVE FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- 사용자가 자신의 todos만 INSERT (추가)할 수 있는 정책
CREATE POLICY "Enable insert for authenticated users" ON public.todos
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 사용자가 자신의 todos만 UPDATE (수정)할 수 있는 정책
CREATE POLICY "Enable update for authenticated users" ON public.todos
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

-- 사용자가 자신의 todos만 DELETE (삭제)할 수 있는 정책
CREATE POLICY "Enable delete for authenticated users" ON public.todos
AS PERMISSIVE FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
